spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8999/realms/deepfitness-oauth/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-detail-service
          uri: lb://USER-DETAIL-SERVICE
          predicates:
            - Path=/api/users/**

        - id: deep-ai-service
          uri: lb://DEEP-AI-SERVICE
          predicates:
            - Path=/api/ai/recommendations/**

        - id: user-activities
          uri: lb://USER-ACTIVITIES
          predicates:
            - Path=/api/activity/**
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/